[theme]
theme =  "solarized-dark"

[icons]
icons = "awesome4"

[[block]]
block = "custom"
interval = "once"
command = "echo ' Run'"
hide_when_empty = false
[[block.click]]
button = "left"
cmd = "i3-dmenu-desktop"

[[block]]
block = "keyboard_layout"
interval = 1
format = "$layout"

[[block]]
block = "sound"
[[block.click]]
button = "left"
cmd = "pavucontrol"

# Ethernet
[[block]]
block = "net"
device = "enp2s0"
format = "  $ssid ↑speed_up ↓$speed_down"
interval = 5

# Wi-Fi
[[block]]
block = "net"
device = "wlan0"
format = "  $ssid "
interval = 5
[[block.click]]
button = "right"
#cmd = "notify-send --expire-time=3000 'Wi-Fi Status' 'SSID: $ssid\nStatus: $icon\nUp: $speed_up\nDown: $speed_down'"
cmd = "~/.config/i3/scripts/show-network-notification.sh"
[[block.click]]
button="left"
cmd = "nm-connection-editor"


[[block]]
block = "battery"
device = "BAT1"
format = "$icon $percentage $time"
interval = 5


[[block]]
block = "time"
interval = 5
format = " $timestamp.datetime(f:'%a %d %b %R') "

[[block]]
block = "custom"
command = "echo \uf011 "
interval = "once"
[[block.click]]
button = "left"
cmd = "~/.config/i3/scripts/dmenu-logout.sh"
